name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
        # can add poetry version here too
      # Run all the matrix jobs, even if one fails.
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        # with:
        #   poetry-version: ${{ matrix.poetry-version }}
      - name: Install mopidy-tidal and enter venv
        run: |
          poetry install
          poetry shell
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test
      - name: Upload coverage
        if: ${{ matrix.python-version  == '3.10' }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
